### ISSUE TITLE
Project 0 Feedback

### ISSUE THREAD

**Issue by micahwierenga** [ricksubel/Whos-Diss-Project-Zero#1]
Rick, it was so great to see all your growth during our first project week, and you created a fun and stylish game! I especially like that you figured out how to use `window.location` while passing the `player` as a query parameter to the next page!

Your project meets all the requirements.

In the next comment, I'll make a couple suggested improvements for the code.

**Comment by micahwierenga** [comment]
With the button click logic, I do think there's a great way to DRY up the code. If you added a custom attribute like `data-target` like this:

```
<div class="grid-item auth" data-target="auth-page"><img src="./Assets/Images/Authors/AuthCat.jpg" alt=""></div>
```

Then you could write just one click listener for all 3 buttons like this:

```
$('.rap .celeb .auth').on('click', function() { 
    const targetPage = $(this).attr('data-target');
    window.location = `./${targetPage}.html?player=${player}`;
});
```

Also, in the following function, it looks like all the conditions run the same logic:

```
const $scoreImg = (score) => {
    if ( score == 0 ) {
        $('.score-text h2').eq(1).css('color', 'white');
    } else if ( score == 1 ) {
        $('.score-text h2').eq(1).css('color', 'white');
    } else if ( score == 2 ) {
        $('.score-text h2').eq(1).css('color', 'white');
    } else if ( score == 3 ) {
        $('.score-text h2').eq(1).css('color', 'white');
    } else if ( score == 4 ) {
        $('.score-text h2').eq(1).css('color', 'white');
    } else if ( score == 5 ) {
        $('.score-text h2').eq(1).css('color', 'white');
    } else if ( score == 6 ) {
        $('.score-text h2').eq(1).css('color', 'white');
    } else if ( score == 7 ) {
        $('.score-text h2').eq(1).css('color', 'white');
    } else if ( score == 8 ) {
        $('.score-text h2').eq(1).css('color', 'white');
    } else if ( score == 9 ) {
        $('.score-text h2').eq(1).css('color', 'white');
    } else {
        $('.score-text h2').eq(1).css('color', 'white');
    }
};
```

Since every condition is going to result in the same action, you can simplify the logic by doing:


```
const $scoreImg = () => {
    $('.score-text h2').eq(1).css('color', 'white');
};
```

Again, fantastic job on your project! Looking forward to seeing more of your work!

**Comment by ricksubel** [comment]
> Rick, it was so great to see all your growth during our first project week, and you created a fun and stylish game! I especially like that you figured out how to use `window.location` while passing the `player` as a query parameter to the next page!
> 
> Your project meets all the requirements.
> 
> In the next comment, I'll make a couple suggested improvements for the code.

Thank you Micah!
